### ISSUE TITLE
获取的邮件内容如果包含中文，会乱码，这个如何解决？

### ISSUE THREAD

**Issue by gnmmdk** [kongpf8848/MailCore2Example#2]
如题

**Comment by kongpf8848** [comment]
中文乱码需要修改MailCore2源码，本demo已经更新，修复了中文乱码的问题，你可以再试一下

**Comment by gnmmdk** [comment]
请问在哪里修改？

**Comment by gnmmdk** [comment]
请问在哪里修改，我想尝试着自己编译一下包

**Comment by gnmmdk** [comment]
![image](https://user-images.githubusercontent.com/18391426/223408363-206342fe-f23f-4784-b16a-fcde1c545746.png)

**Comment by gnmmdk** [comment]
> 中文乱码需要修改MailCore2源码，本demo已经更新，修复了中文乱码的问题，你可以再试一下

还是一样乱码，我收到的是qq邮箱的邮件。
![image](https://user-images.githubusercontent.com/18391426/223597166-b43a4173-1d3c-4d5f-bb3c-f2be4a3077c8.png)

**Comment by gnmmdk** [comment]
请问你编译的ndk是什么版本？我使用官方文档对应的ndk17，openssl对应的version是1.0.2u，但是编译出来的包（openssl-android-3.zip）没有内容.
![image](https://user-images.githubusercontent.com/18391426/223412197-53349a43-b024-43b0-8548-f17b2fce44c3.png)
![image](https://user-images.githubusercontent.com/18391426/223412249-33fe0511-c24b-4e0d-aa56-69e40247da3b.png)

**Comment by gnmmdk** [comment]
> 

如果是附件包含中文名，则中文名是空的，例如：简历.doc 变为  .doc

**Comment by kongpf8848** [comment]
你直接运行本demo试一下，替换用户名和密码，应该可以解决乱码的问题，然后参考本demo修改自己的程序

**Comment by gnmmdk** [comment]
确实可以了，十分感谢🙏
