### ISSUE TITLE
编译mailcore2报错了，希望可以帮忙解答下

### ISSUE THREAD

**Issue by gnmmdk** [kongpf8848/MailCore2Example#3]
我参照官方提供的步骤进行编译。https://github.com/MailCore/mailcore2/blob/master/build-android/README.md
本地使用ndk 20.0.5594570 编译，openssl 为 1.1.1k， libsasl 2.1.27，前面步骤没问题，直到编译build-android/dependencies/cyrus-sasl的脚本，报了错误：
/Users/kangjj/Android/mailcore2-build/libetpan/build-android/dependencies/cyrus-sasl/src/cyrus-sasl-2.1.27/build-android/jni/../../plugins/anonymous.c:55:10: fatal error: 
      'plugin_common.h' file not found
#include "plugin_common.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
请问你知道如何解决吗？

**Comment by kongpf8848** [comment]
sasl版本改为2.1.26试一下
> prepare-cyrus-sasl.sh: Change version in line 5 to version=2.1.26 (to match version with build-android/dependencies/cyrus-sasl/build.sh)
