### ISSUE TITLE
如何使用auth2

### ISSUE THREAD

**Issue by gnmmdk** [kongpf8848/MailCore2Example#4]
你好，使用了你的库，outlook和gmail就没法使用了吗？

**Comment by kongpf8848** [comment]
MailCore2类库支持Outlook、Gmail等走OAuth2认证的邮箱，可参考以下步骤：
1. 走OAuth2流程获取access_token，refresh_token等信息
2. 构建IMAPSession/SMTPSession对象时添加以下代码：
```
 session.setOAuth2Token(access_token);
 //Outlook邮箱
 session.setAuthType(AuthType.AuthTypeXOAuth2Outlook);
 //Gmail等非Outlook邮箱
 session.setAuthType(AuthType.AuthTypeXOAuth2);
```

**Comment by gnmmdk** [comment]
主要是你这里的介绍说不适用，所以才有疑问。
![image](https://user-images.githubusercontent.com/18391426/233879163-d5b0f367-445e-4782-bc07-32ce5023fadc.png)

**Comment by gnmmdk** [comment]
主要是项目中的说明“不适用”，才有了此一问。”此Demo仅适用于QQ邮箱，163邮箱等使用密码/授权码可以直接登录的IMAP/SMTP邮箱，而**需要走OAuth2认证的邮箱则不适用**，如GMail，Outlook等邮箱。“

**Comment by gnmmdk** [comment]
你知道outlook如何申请accesstoken用于邮箱吗？
申请的方式如下：
    var SCOPES = listOf("User.Read")

mMultipleAccountApp?.acquireToken(
            AcquireTokenParameters(
                AcquireTokenParameters.Builder()
                    .startAuthorizationFromActivity(activity)
                    .withScopes(SCOPES)
                    .withCallback(object:AuthenticationCallback{
                        override fun onSuccess(authenticationResult: IAuthenticationResult?) {
                            accessToken = authenticationResult?.accessToken.orEmpty()
                            mFirstAccount = authenticationResult?.account
                            Log.e(TAG,"accessToken1>>>$accessToken")
                            accessTokenCallback.onSuccess(accessToken)
                        }

                        override fun onError(exception: MsalException?) {
                            if (exception is MsalClientException) {
                                exception.printStackTrace()
                            } else if (exception is MsalServiceException) {
                                exception.printStackTrace()
                            }
                            accessTokenCallback.onFail(exception?.errorCode,exception?.localizedMessage)
                        }

                        override fun onCancel() {
                            accessTokenCallback.onCancel()
                        }
                    })))

smtp配置的信息如下：
![image](https://user-images.githubusercontent.com/18391426/233951901-6afeb41f-7897-4261-8302-434f1b4c0da1.png)
但是发送邮件的时候报了验证错误：Unable to authenticate with the current session's credentials.
是我获取token的scope错了吗？

**Comment by kongpf8848** [comment]
我不是很清楚你怎么申请token的，有空我写个demo出来。outlook的oauth2流程可以参考以下链接：
https://learn.microsoft.com/en-us/previous-versions/office/developer/onedrive-live-sdk/dn631818(v=office.15)
scope可以参考下图：
<img width="872" alt="截屏2023-04-24 下午10 32 17" src="https://user-images.githubusercontent.com/25379134/234030627-bbdb2cd0-9892-48ad-b1ca-e68fef9b3fd2.png">

**Comment by gnmmdk** [comment]
微软有提供一个获取token的库https://github.com/AzureAD/microsoft-authentication-library-for-android

**Comment by gnmmdk** [comment]
outlook和gmail的connectType是使用TLS还是StartTLS

**Comment by kongpf8848** [comment]
TLS，[我的掘金主页](https://juejin.cn/user/3808364011199591)，以后有问题在掘金上私信聊吧
